---

- name: Install APT packages
  apt: name={{item}} \
       cache_valid_time=3600
  with_items:
    - python-pip
  become: yes

- name: Install pip packages
  pip: state=present \
       name={{item}}
  with_items:
    - ansible
  become: yes
