---

- name: SSH authorized keys - Set the ssh authorized_keys
  authorized_key: user=pi \
                  key="{{pi_ssh_keys_string}}"
                  manage_dir=yes \
                  state=present \
                  exclusive=yes

- name: Harden the default user password
  user: name=pi \
        password={{ pi_password }}
        system=yes
        state=present
  become: yes

- name: 'Configure WIFI to roaming'
  template: src=wpa_supplicant.j2
            dest={{systemConfigBaseDir}}/wpa_supplicant/wpa_supplicant.conf \
            mode=0600 \
            owner=root
  become: yes
  notify: Restart raspberry pi

- name: Configure options in /boot/config.txt.
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"
  become: yes
#(C) geerlingguy/ansible-role-raspberry-pi
  notify: Restart raspberry pi

- name: Configure options in /etc/rc.local.
  lineinfile:
    dest: /etc/rc.local
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^exit"
    state: present
  with_items: "{{ raspberry_pi_rc_local_options }}"
  become: yes
#(C) geerlingguy/ansible-role-raspberry-pi
  notify: Restart raspberry pi

- name: Set default languages
  locale_gen: name={{item}} state=present
  with_items: "{{raspberry_pi_locales}}"
  become: yes
  notify: Restart raspberry pi

- name: Set default keyboard layout
  lineinfile:
    dest: /etc/default/keyboard
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ raspberry_pi_keyboard_layout }}"
  become: yes
  notify: Restart raspberry pi

- name: Set hostname
  hostname: name="raspberry{{inventory_hostname}}"
  become: yes
  notify: Restart raspberry pi

- name: Set hosts
  lineinfile: dest=/etc/hosts \
              regexp=raspberry
              line="127.0.1.1       raspberry{{inventory_hostname}}"
  become: yes
  notify: Restart raspberry pi

- name: 'Upgrade APT to the latest packages'
  apt: upgrade=safe \
       update_cache=yes
  become: yes

