---
- hosts: zabbix_agent
  become: true

  pre_tasks:
    # zabbix needs permissions to read systemd's log entries. There is currently no way to limit access to a single service only.
    - ansible.builtin.user:
        append: true
        groups:
          - systemd-journal
        name: zabbix

  roles:
    - role: community.zabbix.zabbix_agent
    - role: ansible-role-zabbix-agent2-plugin
      zbxp_plugin_name: "ZBX_Journald"
      zbxp_plugin_repository_binary_url: https://github.com/Hypernova-Oy/zabbix-agent2-plugin-journald/releases/download/v0.0.1/zabbix-agent2-plugin-journald.arm
      zbxp_plugin_configurations:
        - directive: Plugins.{{zbxp_plugin_name}}.Test
          value: 1

