---

- name: Restart raspberry pi
  command: shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  notify: Wait for Raspberry PI to come back

- name: Wait for Raspberry PI to come back
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=20
